### ISSUE TITLE
thumbv6m: debug assertion in divmoddi4

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/compiler-builtins#150]
``` rust
#[test]
fn divmoddi4() {
    let (a, b) = (4165187992, 3876330169);
    let mut rem = 0;
    let c = __divmoddi4(a, b, &mut rem_);
}
```

```
$ qemu-arm target/thumbv6m-linux-eabi/debug/divmoddi4-04f11ecf75829660
running 1 tests
test divmoddi4 ...
panicked at 'attempt to multiply with overflow', /home/japaric/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/9681358/src/int/udiv.rs:95
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
[1]    21208 illegal hardware instruction (core dumped)  qemu-arm target/thumbv6m-linux-eabi/debug/divmoddi4-04f11ecf75829660
```

thumbv7m targets don't have this problem.

**Comment by japaric** [comment]
Another case that results in an assertion `(1750458948, 2611493155)` with `divdi3`.

**Comment by japaric** [comment]
Testing all these intrinsics fail due to this debug assertion

- divdi3
- divmoddi4
- moddi3
- modsi3
- udivmoddi4
- udivmodsi4
- umoddi3
- umodsi3

**Comment by parched** [comment]
This is probably fix by https://github.com/rust-lang/llvm/pull/79

**Comment by parched** [comment]
@japaric I think this should be fixed in the latest nightly now that https://github.com/rust-lang/rust/pull/42410 has landed.

**Comment by japaric** [comment]
I tested with `rustc 1.19.0-nightly (fe7227f6c 2017-06-16)` and I'm still seeing the debug assertion. I'll try again with the next nightly release.

**Comment by parched** [comment]
Ok, that commit had the fix in, so this must be caused by something else.

**Comment by parched** [comment]
@japaric I'd like to debug this, how exactly did you run the test? Do I have to build all of std with Xargo for `thumbv6m-linux-eabi`?

**Comment by japaric** [comment]
@parched I actually ran the whole test suite with `sh ci/run.sh thumbv6m-linux-eabi`. But you can run a single custom test like this:

``` console
$ edit tests/custom.rs && cat $_
```

``` rust
#![feature(compiler_builtins_lib)]
#![no_std]

extern crate compiler_builtins;
extern crate utest_cortex_m_qemu;
#[macro_use]
extern crate utest_macros;

macro_rules! panic {
    ($($tt:tt)*) => {
        upanic!($($tt)*);
    };
}

use compiler_builtins::int::sdiv::__divmoddi4;

#[test]
fn divmoddi4() {
    let (a, b) = (4165187992, 3876330169);
    let mut rem = 0;
    let c = __divmoddi4(a, b, &mut rem);
}
```

``` console
$ xargo test --test custom --target thumbv6m-linux-eabi --features 'mem gen-tests' --no-run
$ qemu-arm target/thumbv6m-linux-eabi/debug/custom-6bc70d2d2f80ab1e
running 1 tests
test divmoddi4 ...
panicked at 'attempt to multiply with overflow', src/int/udiv.rs:95
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
[1]    27726 illegal hardware instruction (core dumped)  qemu-arm target/thumbv6m-linux-eabi/debug/custom-6bc70d2d2f80ab1e
```

**Comment by parched** [comment]
Ok, I've debugged it and looks like LLVM bug for unsigned multiplication with overflow. I'll make a patch.

**Comment by japaric** [comment]
Thanks for investigating and working on this @parched ❤️

**Comment by parched** [comment]
No problem, the fix has been accepted upstream. Once https://github.com/rust-lang/llvm/issues/85 is merged and rust is updated hopefully this will be fixed.

**Comment by parched** [comment]
@japaric Do some tests need to be re-enabled now?

**Comment by japaric** [comment]
@parched Yes. I'll send a PR later today. (I suspect a nightly with the fix may not be out yet.)
